language: java
jdk:
  - oraclejdk8

# setting install to true to avoid unnecessary build
install: true

notifications:
  email:
    recipients:
      - andre.behrens@haw-hamburg.de
      
# Scripts
script: 
- mvn clean install
- java -jar target/benchmarks.jar
