language: java
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - andre.behrens@haw-hamburg.de
      
# Scripts
script: 
- mvn clean install
- mvn test
- java -jar target/benchmarks.jar
