language: java
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - andre.behrens@haw-hamburg.de
      
# Scripts
script: 
- mvn -Dmaven.test.failure.ignore=true --fail-at-end clean install
- java -jar target/benchmarks.jar
